name: ToDoLister
services: 
  frontend:
    build: ./Frontend/
    image: soblbth/todo-webpage:latest
    ports: ['8000:8000']
    volumes: ['./Frontend/:/app']
    environment: 
      FLASK_RUN_PORT: 8000
      BACKEND: backend
      BACKEND_PORT: 8001
  
  backend:
    depends_on:
      - mysql_db
    restart: on-failure:10
    build: ./Backend/
    image: soblbth/todo-handler:latest
    expose:
      - 8001
    volumes: [./Backend/:/server]
    environment:
      FLASK_RUN_PORT: 8001
      DATABASE_HOST: mysql_db
      DATABSE_USER: not_root
      DATABASE_PASSWORD: example
      DATABASE_PORT: 3306
      DATABASE_DB: Notebook

  mysql_db:
    hostname: mysql_db
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: Notebook
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: not_root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: "%"  # Allows other network entities to connect to the database
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    expose:
      - 3306